apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: demo-express
  name: demo-express
spec:
  source:
    git:
      ref: master
      uri: https://github.com/gary-jipp/demo-openshift-express
      contextDir: app
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:16-ubi8-minimal'
  output:
    to:
      kind: ImageStreamTag
      name: demo-express:latest
