apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: demo-express
  name: demo-express
spec:
  source:
    contextDir: app
    git:
      ref: master
      uri: https://github.com/gary-jipp/demo-openshift-express
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: node:16-alpine
  output:
    to:
      kind: ImageStreamTag
      name: demo-express:latest
