kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"demo-express:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"demo-express\")].image"}]'
  name: demo-express
  namespace: crt-redhat2304-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: demo-express
  template:
    metadata:
      labels:
        deployment: demo-express
    spec:
      containers:
        - name: demo-express
          image: 'demo-express:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
