apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: my-tasks
spec:
  steps:
    - name: my-step1
      image: alpine:3.14
      script: |
        echo "Running Step 1"
    - name: my-step2
      image: alpine:3.14
      script: |
        echo "Running Step 2"
