apiVersion: v1
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: simple-web-app
parameters:
- name: APP_NAME
  description: The name of the application
  required: true
  value: simple-web-app
- name: IMAGE_TAG
  description: The tag of the Docker image to use
  required: true
  value: latest
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
  spec:
    selector:
      app: ${APP_NAME}
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${APP_NAME}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
        - name: ${APP_NAME}
          image: nginx:${IMAGE_TAG}
          ports:
          - containerPort: 80
