apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-express
spec:
  source:
    git:
      uri: https://github.com/gary-jipp/demo-express-openshift
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:16-ubi8-minimal'
  output:
    to:
      kind: ImageStreamTag
      name: demo-express:latest
