name: mcap-demo build
on:
  push:
    paths:
      - "*.js"
      - "Dockerfile"
      - "package*.json"
      - "**/*.yaml"
    # paths-ignore:
    #   - '**/*.md'
  workflow_dispatch:
defaults:
  run:
    working-directory: .
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Unit tests
        run: npm run test --if-present
  build:
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: npm install and build
        run: |
          npm ci --if-present
          npm run build --if-present
        env:
          CI: "true"
  s2i-build:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: S2I Build
        env:
          NAMESPACE: ${{ secrets.OpenShiftNamespace }}
          BUILD_NAME: demo-express
          IMAGE_NAME: demo-express
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'get imagestreams'
            'start-build ${BUILD_NAME}  --follow'
            'tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:latest ${NAMESPACE}/${IMAGE_NAME}:dev'
